
// This file has been generated by the GUI designer. Do not modify.
namespace ConvaysGameOfLife
{
	public partial class ConfigWindow
	{
		private global::Gtk.Table table2;
		private global::Gtk.ComboBox cbDesigners;
		private global::Gtk.ComboBox cbNeighbourhoods;
		private global::Gtk.ComboBox cbRules;
		private global::Gtk.HBox hbox1;
		private global::Gtk.Button buttonAccept;
		private global::Gtk.Button buttonCancel;
		private global::Gtk.Label label1;
		private global::Gtk.Label label10;
		private global::Gtk.Label label12;
		private global::Gtk.Label label2;
		private global::Gtk.Label label3;
		private global::Gtk.Label label9;
		private global::Gtk.Label labelDim;
		private global::Gtk.Label labelNeigh;
		private global::Gtk.SpinButton sbCols;
		private global::Gtk.SpinButton sbInterval;
		private global::Gtk.SpinButton sbRows;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget ConvaysGameOfLife.ConfigWindow
			this.Name = "ConvaysGameOfLife.ConfigWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("ConfigWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child ConvaysGameOfLife.ConfigWindow.Gtk.Container+ContainerChild
			this.table2 = new global::Gtk.Table (((uint)(12)), ((uint)(3)), false);
			this.table2.Name = "table2";
			this.table2.RowSpacing = ((uint)(6));
			this.table2.ColumnSpacing = ((uint)(6));
			this.table2.BorderWidth = ((uint)(6));
			// Container child table2.Gtk.Table+TableChild
			this.cbDesigners = global::Gtk.ComboBox.NewText ();
			this.cbDesigners.Name = "cbDesigners";
			this.table2.Add (this.cbDesigners);
			global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.table2 [this.cbDesigners]));
			w1.TopAttach = ((uint)(10));
			w1.BottomAttach = ((uint)(11));
			w1.LeftAttach = ((uint)(1));
			w1.RightAttach = ((uint)(2));
			w1.XOptions = ((global::Gtk.AttachOptions)(4));
			w1.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.cbNeighbourhoods = global::Gtk.ComboBox.NewText ();
			this.cbNeighbourhoods.Name = "cbNeighbourhoods";
			this.table2.Add (this.cbNeighbourhoods);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table2 [this.cbNeighbourhoods]));
			w2.TopAttach = ((uint)(6));
			w2.BottomAttach = ((uint)(7));
			w2.LeftAttach = ((uint)(1));
			w2.RightAttach = ((uint)(2));
			w2.XOptions = ((global::Gtk.AttachOptions)(4));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.cbRules = global::Gtk.ComboBox.NewText ();
			this.cbRules.Name = "cbRules";
			this.table2.Add (this.cbRules);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table2 [this.cbRules]));
			w3.TopAttach = ((uint)(8));
			w3.BottomAttach = ((uint)(9));
			w3.LeftAttach = ((uint)(1));
			w3.RightAttach = ((uint)(2));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.buttonAccept = new global::Gtk.Button ();
			this.buttonAccept.CanFocus = true;
			this.buttonAccept.Name = "buttonAccept";
			this.buttonAccept.UseUnderline = true;
			this.buttonAccept.Label = global::Mono.Unix.Catalog.GetString ("Accpet");
			this.hbox1.Add (this.buttonAccept);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.buttonAccept]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = global::Mono.Unix.Catalog.GetString ("Cancel");
			this.hbox1.Add (this.buttonCancel);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.buttonCancel]));
			w5.Position = 2;
			w5.Expand = false;
			w5.Fill = false;
			this.table2.Add (this.hbox1);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table2 [this.hbox1]));
			w6.TopAttach = ((uint)(11));
			w6.BottomAttach = ((uint)(12));
			w6.LeftAttach = ((uint)(1));
			w6.RightAttach = ((uint)(2));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.Xalign = 0F;
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Seed Designer");
			this.table2.Add (this.label1);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table2 [this.label1]));
			w7.TopAttach = ((uint)(9));
			w7.BottomAttach = ((uint)(10));
			w7.XOptions = ((global::Gtk.AttachOptions)(4));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label10 = new global::Gtk.Label ();
			this.label10.Name = "label10";
			this.label10.Xalign = 0F;
			this.label10.LabelProp = global::Mono.Unix.Catalog.GetString ("Columns");
			this.table2.Add (this.label10);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table2 [this.label10]));
			w8.TopAttach = ((uint)(2));
			w8.BottomAttach = ((uint)(3));
			w8.LeftAttach = ((uint)(1));
			w8.RightAttach = ((uint)(2));
			w8.XOptions = ((global::Gtk.AttachOptions)(4));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label12 = new global::Gtk.Label ();
			this.label12.Name = "label12";
			this.label12.Xalign = 0F;
			this.label12.LabelProp = global::Mono.Unix.Catalog.GetString ("Rules");
			this.table2.Add (this.label12);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table2 [this.label12]));
			w9.TopAttach = ((uint)(7));
			w9.BottomAttach = ((uint)(8));
			w9.XOptions = ((global::Gtk.AttachOptions)(4));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.Xalign = 0F;
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Ticks");
			this.table2.Add (this.label2);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table2 [this.label2]));
			w10.TopAttach = ((uint)(3));
			w10.BottomAttach = ((uint)(4));
			w10.XOptions = ((global::Gtk.AttachOptions)(4));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.Xalign = 0F;
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Interval (ms)");
			this.table2.Add (this.label3);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table2 [this.label3]));
			w11.TopAttach = ((uint)(4));
			w11.BottomAttach = ((uint)(5));
			w11.LeftAttach = ((uint)(1));
			w11.RightAttach = ((uint)(2));
			w11.XOptions = ((global::Gtk.AttachOptions)(4));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label9 = new global::Gtk.Label ();
			this.label9.Name = "label9";
			this.label9.Xalign = 0F;
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString ("Rows");
			this.table2.Add (this.label9);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table2 [this.label9]));
			w12.TopAttach = ((uint)(1));
			w12.BottomAttach = ((uint)(2));
			w12.LeftAttach = ((uint)(1));
			w12.RightAttach = ((uint)(2));
			w12.XOptions = ((global::Gtk.AttachOptions)(4));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.labelDim = new global::Gtk.Label ();
			this.labelDim.Name = "labelDim";
			this.labelDim.Xalign = 0F;
			this.labelDim.LabelProp = global::Mono.Unix.Catalog.GetString ("Dimensions");
			this.table2.Add (this.labelDim);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table2 [this.labelDim]));
			w13.XOptions = ((global::Gtk.AttachOptions)(4));
			w13.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.labelNeigh = new global::Gtk.Label ();
			this.labelNeigh.Name = "labelNeigh";
			this.labelNeigh.Xalign = 0F;
			this.labelNeigh.LabelProp = global::Mono.Unix.Catalog.GetString ("Neighbourhood");
			this.table2.Add (this.labelNeigh);
			global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table2 [this.labelNeigh]));
			w14.TopAttach = ((uint)(5));
			w14.BottomAttach = ((uint)(6));
			w14.XOptions = ((global::Gtk.AttachOptions)(4));
			w14.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.sbCols = new global::Gtk.SpinButton (0, 1000, 1);
			this.sbCols.CanFocus = true;
			this.sbCols.Name = "sbCols";
			this.sbCols.Adjustment.PageIncrement = 10;
			this.sbCols.ClimbRate = 1;
			this.sbCols.Numeric = true;
			this.table2.Add (this.sbCols);
			global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table2 [this.sbCols]));
			w15.TopAttach = ((uint)(2));
			w15.BottomAttach = ((uint)(3));
			w15.LeftAttach = ((uint)(2));
			w15.RightAttach = ((uint)(3));
			w15.XOptions = ((global::Gtk.AttachOptions)(4));
			w15.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.sbInterval = new global::Gtk.SpinButton (0, 5000, 1);
			this.sbInterval.CanFocus = true;
			this.sbInterval.Name = "sbInterval";
			this.sbInterval.Adjustment.PageIncrement = 10;
			this.sbInterval.ClimbRate = 1;
			this.sbInterval.Numeric = true;
			this.table2.Add (this.sbInterval);
			global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.table2 [this.sbInterval]));
			w16.TopAttach = ((uint)(4));
			w16.BottomAttach = ((uint)(5));
			w16.LeftAttach = ((uint)(2));
			w16.RightAttach = ((uint)(3));
			w16.XOptions = ((global::Gtk.AttachOptions)(4));
			w16.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.sbRows = new global::Gtk.SpinButton (0, 1000, 1);
			this.sbRows.CanFocus = true;
			this.sbRows.Name = "sbRows";
			this.sbRows.Adjustment.PageIncrement = 10;
			this.sbRows.ClimbRate = 1;
			this.sbRows.Numeric = true;
			this.table2.Add (this.sbRows);
			global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.table2 [this.sbRows]));
			w17.TopAttach = ((uint)(1));
			w17.BottomAttach = ((uint)(2));
			w17.LeftAttach = ((uint)(2));
			w17.RightAttach = ((uint)(3));
			w17.XOptions = ((global::Gtk.AttachOptions)(4));
			w17.YOptions = ((global::Gtk.AttachOptions)(4));
			this.Add (this.table2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 311;
			this.DefaultHeight = 345;
			this.Show ();
			this.buttonAccept.Clicked += new global::System.EventHandler (this.buttonAccept_onClicked);
			this.buttonCancel.Clicked += new global::System.EventHandler (this.buttonCancel_onClicked);
		}
	}
}
