
// This file has been generated by the GUI designer. Do not modify.
namespace ConvaysGameOfLife
{
	public partial class VisualSeedDesigner
	{
		private global::Gtk.VBox vbox1;
		private global::Gtk.EventBox eventbox1;
		private global::Gtk.Image image1;
		private global::Gtk.HBox hbox1;
		private global::Gtk.Button buttonAccept;
		private global::Gtk.Button buttonCancel;
		private global::Gtk.Button buttonClear;
		private global::Gtk.Statusbar statusbar1;
		private global::Gtk.Label labelX;
		private global::Gtk.Label labelY;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget ConvaysGameOfLife.VisualSeedDesigner
			this.Name = "ConvaysGameOfLife.VisualSeedDesigner";
			this.Title = global::Mono.Unix.Catalog.GetString ("VisualSeedDesigner");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child ConvaysGameOfLife.VisualSeedDesigner.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.eventbox1 = new global::Gtk.EventBox ();
			this.eventbox1.Name = "eventbox1";
			// Container child eventbox1.Gtk.Container+ContainerChild
			this.image1 = new global::Gtk.Image ();
			this.image1.Name = "image1";
			this.eventbox1.Add (this.image1);
			this.vbox1.Add (this.eventbox1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.eventbox1]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.buttonAccept = new global::Gtk.Button ();
			this.buttonAccept.CanFocus = true;
			this.buttonAccept.Name = "buttonAccept";
			this.buttonAccept.UseUnderline = true;
			this.buttonAccept.Label = global::Mono.Unix.Catalog.GetString ("Accept");
			this.hbox1.Add (this.buttonAccept);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.buttonAccept]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = global::Mono.Unix.Catalog.GetString ("Cancel");
			this.hbox1.Add (this.buttonCancel);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.buttonCancel]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.buttonClear = new global::Gtk.Button ();
			this.buttonClear.CanFocus = true;
			this.buttonClear.Name = "buttonClear";
			this.buttonClear.UseUnderline = true;
			this.buttonClear.Label = global::Mono.Unix.Catalog.GetString ("Clear");
			this.hbox1.Add (this.buttonClear);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.buttonClear]));
			w5.Position = 2;
			w5.Expand = false;
			w5.Fill = false;
			this.vbox1.Add (this.hbox1);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.statusbar1 = new global::Gtk.Statusbar ();
			this.statusbar1.Name = "statusbar1";
			this.statusbar1.Spacing = 6;
			// Container child statusbar1.Gtk.Box+BoxChild
			this.labelX = new global::Gtk.Label ();
			this.labelX.Name = "labelX";
			this.labelX.LabelProp = global::Mono.Unix.Catalog.GetString ("label1");
			this.statusbar1.Add (this.labelX);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.statusbar1 [this.labelX]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			// Container child statusbar1.Gtk.Box+BoxChild
			this.labelY = new global::Gtk.Label ();
			this.labelY.Name = "labelY";
			this.labelY.LabelProp = global::Mono.Unix.Catalog.GetString ("label2");
			this.statusbar1.Add (this.labelY);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.statusbar1 [this.labelY]));
			w8.Position = 2;
			w8.Expand = false;
			w8.Fill = false;
			this.vbox1.Add (this.statusbar1);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.statusbar1]));
			w9.Position = 2;
			w9.Expand = false;
			w9.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
			this.MapEvent += new global::Gtk.MapEventHandler (this.VisualSeedDesigner_onmapEvent);
			this.eventbox1.ButtonReleaseEvent += new global::Gtk.ButtonReleaseEventHandler (this.eventBox_onButtonRelease);
			this.buttonAccept.Clicked += new global::System.EventHandler (this.ButtonAccept_onClicked);
			this.buttonCancel.Clicked += new global::System.EventHandler (this.buttonCancel_onClicked);
			this.buttonClear.Clicked += new global::System.EventHandler (this.buttonClear_onClicked);
		}
	}
}
