
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	private global::Gtk.Action FileAction;
	private global::Gtk.Action revertToSavedAction;
	private global::Gtk.Action newAction;
	private global::Gtk.Action quitAction;
	private global::Gtk.Action RunAction;
	private global::Gtk.Action CurrentAction;
	private global::Gtk.Action CurrentAction1;
	private global::Gtk.Action DropCurrentAction;
	private global::Gtk.Action Action;
	private global::Gtk.Action NewRandomAction;
	private global::Gtk.VBox vbox1;
	private global::Gtk.MenuBar menubar1;
	private global::Gtk.Image image1;
	private global::Gtk.HBox hbox1;
	private global::Gtk.Button buttonStart;
	private global::Gtk.Button buttonStop;
	private global::Gtk.Button buttonPause;
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	private global::Gtk.TextView outputTextview;
	private global::Gtk.Statusbar statusbar1;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.FileAction = new global::Gtk.Action ("FileAction", global::Mono.Unix.Catalog.GetString ("File"), null, null);
		this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("File");
		w1.Add (this.FileAction, null);
		this.revertToSavedAction = new global::Gtk.Action ("revertToSavedAction", global::Mono.Unix.Catalog.GetString ("Load"), null, "gtk-revert-to-saved");
		this.revertToSavedAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Load");
		w1.Add (this.revertToSavedAction, null);
		this.newAction = new global::Gtk.Action ("newAction", global::Mono.Unix.Catalog.GetString ("New"), null, "gtk-new");
		this.newAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("New");
		w1.Add (this.newAction, null);
		this.quitAction = new global::Gtk.Action ("quitAction", global::Mono.Unix.Catalog.GetString ("Quit"), null, "gtk-quit");
		this.quitAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Quit");
		w1.Add (this.quitAction, null);
		this.RunAction = new global::Gtk.Action ("RunAction", global::Mono.Unix.Catalog.GetString ("Run"), null, null);
		this.RunAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Run");
		w1.Add (this.RunAction, null);
		this.CurrentAction = new global::Gtk.Action ("CurrentAction", global::Mono.Unix.Catalog.GetString ("Current"), null, null);
		this.CurrentAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Current");
		w1.Add (this.CurrentAction, null);
		this.CurrentAction1 = new global::Gtk.Action ("CurrentAction1", global::Mono.Unix.Catalog.GetString ("Current"), null, null);
		this.CurrentAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("Current");
		w1.Add (this.CurrentAction1, null);
		this.DropCurrentAction = new global::Gtk.Action ("DropCurrentAction", global::Mono.Unix.Catalog.GetString ("Drop Current"), null, null);
		this.DropCurrentAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Drop Current");
		w1.Add (this.DropCurrentAction, null);
		this.Action = new global::Gtk.Action ("Action", null, null, null);
		w1.Add (this.Action, null);
		this.NewRandomAction = new global::Gtk.Action ("NewRandomAction", global::Mono.Unix.Catalog.GetString ("New Random"), null, null);
		this.NewRandomAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("New Random");
		w1.Add (this.NewRandomAction, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.Resizable = false;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 10;
		this.vbox1.BorderWidth = ((uint)(10));
		// Container child vbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><menubar name='menubar1'><menu name='FileAction' action='FileAction'><menuitem name='revertToSavedAction' action='revertToSavedAction'/><menuitem name='newAction' action='newAction'/><menuitem name='quitAction' action='quitAction'/></menu><menu name='RunAction' action='RunAction'><menuitem name='CurrentAction1' action='CurrentAction1'/><menuitem name='DropCurrentAction' action='DropCurrentAction'/></menu></menubar></ui>");
		this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar1")));
		this.menubar1.Name = "menubar1";
		this.vbox1.Add (this.menubar1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.menubar1]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.image1 = new global::Gtk.Image ();
		this.image1.Name = "image1";
		this.vbox1.Add (this.image1);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.image1]));
		w3.Position = 1;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.buttonStart = new global::Gtk.Button ();
		this.buttonStart.CanFocus = true;
		this.buttonStart.Name = "buttonStart";
		this.buttonStart.UseUnderline = true;
		this.buttonStart.Label = global::Mono.Unix.Catalog.GetString ("Start");
		this.hbox1.Add (this.buttonStart);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.buttonStart]));
		w4.Position = 0;
		w4.Expand = false;
		w4.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.buttonStop = new global::Gtk.Button ();
		this.buttonStop.CanFocus = true;
		this.buttonStop.Name = "buttonStop";
		this.buttonStop.UseUnderline = true;
		this.buttonStop.Label = global::Mono.Unix.Catalog.GetString ("Stop");
		this.hbox1.Add (this.buttonStop);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.buttonStop]));
		w5.Position = 1;
		w5.Expand = false;
		w5.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.buttonPause = new global::Gtk.Button ();
		this.buttonPause.CanFocus = true;
		this.buttonPause.Name = "buttonPause";
		this.buttonPause.UseUnderline = true;
		this.buttonPause.Label = global::Mono.Unix.Catalog.GetString ("Pause");
		this.hbox1.Add (this.buttonPause);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.buttonPause]));
		w6.Position = 2;
		w6.Expand = false;
		w6.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.outputTextview = new global::Gtk.TextView ();
		this.outputTextview.CanFocus = true;
		this.outputTextview.Name = "outputTextview";
		this.GtkScrolledWindow.Add (this.outputTextview);
		this.hbox1.Add (this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.GtkScrolledWindow]));
		w8.Position = 3;
		this.vbox1.Add (this.hbox1);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
		w9.Position = 2;
		w9.Expand = false;
		w9.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.statusbar1 = new global::Gtk.Statusbar ();
		this.statusbar1.Name = "statusbar1";
		this.statusbar1.Spacing = 6;
		this.vbox1.Add (this.statusbar1);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.statusbar1]));
		w10.PackType = ((global::Gtk.PackType)(1));
		w10.Position = 3;
		w10.Expand = false;
		w10.Fill = false;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 821;
		this.DefaultHeight = 650;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.MapEvent += new global::Gtk.MapEventHandler (this.MainWindow_onmapEvent);
		this.newAction.Activated += new global::System.EventHandler (this.menuItemNew_onActivated);
		this.buttonStart.Clicked += new global::System.EventHandler (this.buttonStart_onClicked);
		this.buttonStop.Clicked += new global::System.EventHandler (this.buttonStop_onClick);
	}
}
