
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;
	private global::Gtk.Image image1;
	private global::Gtk.HBox hbox1;
	private global::Gtk.Button buttonStart;
	private global::Gtk.Button buttonStop;
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	private global::Gtk.TextView outputTextview;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 10;
		this.vbox1.BorderWidth = ((uint)(10));
		// Container child vbox1.Gtk.Box+BoxChild
		this.image1 = new global::Gtk.Image ();
		this.image1.Name = "image1";
		this.vbox1.Add (this.image1);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.image1]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.buttonStart = new global::Gtk.Button ();
		this.buttonStart.CanFocus = true;
		this.buttonStart.Name = "buttonStart";
		this.buttonStart.UseUnderline = true;
		this.buttonStart.Label = global::Mono.Unix.Catalog.GetString ("Start");
		this.hbox1.Add (this.buttonStart);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.buttonStart]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.buttonStop = new global::Gtk.Button ();
		this.buttonStop.CanFocus = true;
		this.buttonStop.Name = "buttonStop";
		this.buttonStop.UseUnderline = true;
		this.buttonStop.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
		this.hbox1.Add (this.buttonStop);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.buttonStop]));
		w3.Position = 1;
		w3.Expand = false;
		w3.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.outputTextview = new global::Gtk.TextView ();
		this.outputTextview.CanFocus = true;
		this.outputTextview.Name = "outputTextview";
		this.GtkScrolledWindow.Add (this.outputTextview);
		this.hbox1.Add (this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.GtkScrolledWindow]));
		w5.Position = 2;
		this.vbox1.Add (this.hbox1);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
		w6.Position = 1;
		w6.Expand = false;
		w6.Fill = false;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 808;
		this.DefaultHeight = 629;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.MapEvent += new global::Gtk.MapEventHandler (this.MainWindow_onmapEvent);
		this.buttonStart.Clicked += new global::System.EventHandler (this.buttonStart_onClicked);
		this.buttonStop.Clicked += new global::System.EventHandler (this.buttonStop_onClick);
	}
}
